---
# Source: strimzi-kafka-operator/templates/020-RoleBinding-strimzi-cluster-operator.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-cluster-operator
  namespace: kafka
  labels:
    app: strimzi
    chart: strimzi-kafka-operator-0.49.0
    component: role-binding
    release: strimzi-kafka-operator
    heritage: Helm
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: kafka
roleRef:
  kind: Role
  name: full-access-role
  apiGroup: rbac.authorization.k8s.io
