apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: full-access-role
  namespace: kafka
  labels:
    app: strimzi
    chart: strimzi-kafka-operator-0.49.0
    component: role
    release: strimzi-kafka-operator
    heritage: Helm
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]