apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: second-kafka-cluster-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: first-kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824