apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-strimzi
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sambo2021/helm-charts.git
    path: charts/kafka-strimzi/strimzi-kafka-operator/
    targetRevision: master
    helm:
      values: |
        rbac:
          create: false
        createGlobalResources: false
        watchNamespaces: {kafka}
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      selfHeal: true