# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: testing-apps
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/sambo2021/helm-charts.git
#     path: charts/testing-apps/
#     targetRevision: master
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: testing-apps
#   syncPolicy:
#     automated:
#       selfHeal: true