# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: tls-gateway
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/sambo2021/helm-charts.git
#     path: charts/tls-gateway/
#     targetRevision: master
#   destination:
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated:
#       selfHeal: true